### ISSUE TITLE
Universal Work Queue not advancing to correct page

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#106]
Responsibility: PBS US Depot Repair
Navigation:
Universal Work Queue
Click on Configuration from left side
Click on any Configuration Number
Click on the Note's Ok button
[Universal Work Queue 1.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7197301/Universal.Work.Queue.1.docx)
n

**Comment by vinaytalasila** [comment]
Linda,

I tried to reproduce this issue in INT 12.2.10 instance but from my end I am unable to do that. It looks like the issue is at the specific user or users. Attached screenshot below.

![image](https://user-images.githubusercontent.com/84878630/134079197-184c46e6-735f-49cd-86a1-a48e9268d892.png)

So, can we have a Teams meeting now or tomorrow(9/21/2021) at 10:30 AM EDT so that we can go through this and see whether you can reproduce this in INT 12.2.10 instance as well for our troubleshooting.

Thanks
Vinay

**Comment by lindamrigo** [comment]
The bounce corrected the problem

**Comment by lindamrigo** [comment]
the functionality is now behaving as it was on Monday

**Comment by vinaytalasila** [comment]
Linda,

I have scheduled a Teams meeting with Sherry Fischer and you tomorrow at 10:30 AM EDT.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Just an update...Tina will look into this and help the users. I have cancelled Teams meeting with Sherry Fischer.

Thanks
Vinay

**Comment by TinaGriffin** [comment]
There are profiles set at the responsibility level (PBS Automotive Customer Support).  These profiles are IEU%Queue%  These are what determine what shows on the service Universal Work Queue.  We set the subsections to NO in INT for those we don't want to see (they are all HTML subsections), and it's working as expected.  This ticket can be closed.

**Comment by lindamrigo** [comment]
Verified Production is no longer having an issue
