### ISSUE TITLE
502 Bad Gateway for TPQS2I ***SR 3-26106308971***

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#23]
502 Bad Gateway for TPQS2I
![Bad Gateway](https://user-images.githubusercontent.com/85238444/120635187-2f8f4d80-c43a-11eb-83b2-e60200e9c212.JPG)

**Comment by lindamrigo** [comment]
The site is now up and working.

**Comment by amitjori** [comment]
Checking with Oracle for root cause

**Comment by amitjori** [comment]
Below is the reply fro Oracle on root cause analysis 

 Hello Amit,I'm following up on my request yesterday, added here again. I could find no known issues or changes that were done on the Oracle side, but it's possible that the following occurred when the backendset was updated. Updating backendsets will reload the configuration and cause active connections to be interrupted, at which point clients will retry their connections. I saw an ADD_BACKEND work request performed by the LB's admin that might have led to this. This is a known issue and is being worked on for improvement by development to make the update more dynamic without interruption.Updating the backend set can also cause the status in the console to change to critical, given that you only have one backend. However, this should not affect retried connections (outside of the original disconnect).Please let me know more about the original issue you experienced and I will look for more information based on that. Thank you.Regards,Jack
