### ISSUE TITLE
INT Sales User:  Open the page get Error

### ISSUE THREAD

**Issue by SherryXLiu** [Fujitsu-America/Fujitsu-Repository#40]
**Describe the bug**

**Instance Name**
Instance: dpqs2i

**Responsibility Name**
Responsibility:

**Navigation**
Navigation: sales User

**To Reproduce**
![image](https://user-images.githubusercontent.com/85246030/121422475-443d7b00-c93d-11eb-83e7-534c12aa5de1.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment]
Sherry,

We will look into this and keep you posted.

**@suhas-deshpande :** Could you please check what technical / functional setups are missing related to this issue in INT 12.2.10 vs STG 12.2.10 and apply them in INT 12.2.10. If there are any configurations that need to be done by DBA team then please add Amit and Somu to this ticket.

Thanks
Vinay Talasila

**Comment by suhas-deshpande** [comment]
Hi Sherry - Please check now. You should be able to open the page now. You resource id was not mapped to your user in  DPQS2I which has now been fixed.

Thanks,
Suhas

**Comment by SherryXLiu** [comment]
@suhas-deshpande : Yes. It works now. 
Could you provide the fix screenshot? I would understand why it is occurred and if other users could face same problem 
Thanks

**Comment by suhas-deshpande** [comment]
@SherryXLiu  :- While debugging various issues In INT, I had attached my user with your resource  from below navigation to be able to access the forms and responsibilities -

CRM resource Manager - Maintain Resources - Resources. 

Due to this you got the error of invalid resource id. I have now attached your user correctly and going forward I will not need to change it as I already have mine in place.
