### ISSUE TITLE
problem with loading an  OAF form  - SR 3-26106733871

### ISSUE THREAD

**Issue by vinaytalasila** [Fujitsu-America/Fujitsu-Repository#8]
**Describe the bug**
From: Rigo, Linda M <Linda.M.Rigo@snapon.com> 
Sent: Thursday, May 27, 2021 5:29 PM
To: Jori, Amit <Amit.Jori@fujitsu.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>
Cc: Griffin, Tina <Tina.Griffin@snapon.com>; Hamilton, Mark W <Mark.W.Hamilton@snapon.com>; Liu, Sherry X <Sherry.X.Liu@snapon.com>
Subject: 12.2.10 Upgrade Error - Sales User

Hi Amit and Somu
I have found the following problem with loading an  OAF form

Sales User>Sales Search
![image](https://user-images.githubusercontent.com/84878630/120483694-f8f0fe80-c377-11eb-9909-96647a4fc3e4.png)
 

In 12.1.3 – it does force you to log in again but you get  

In 12.2.10
I get
 
![image](https://user-images.githubusercontent.com/84878630/120483595-e080e400-c377-11eb-824c-109953df6ed5.png)

I will try other OAF forms

Linda

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lindamrigo** [comment]
This is still a problem
Responsibility > PBS US Automotive Customer Support>Service Snapshot

**Comment by lindamrigo** [comment]
I have found that there is a patch available for 12.2.10 for OAF 10g. However, even with the patch, there is a possibility that the forms will not work due to the jdk version that is being run (jdk 8) .  The issues with jdk 8 and the patch below have already been logged with Oracle from other people's upgrade experiences.  We can apply the patch and see if that works, but as the important snapshots have already been converted to Apex and the remaining 2 can be converted to Apex, this may not be necessary 

Patch 31640893: 10G JDEVELOPER WITH OA EXTENSION ARU FOR R12.2.10

**Comment by vinaytalasila** [comment]
Just an update... @amitjori will check the patch that was mentioned by Linda in the above comments and update us.

**Comment by amitjori** [comment]
Hi Team,

The size of this patch(31640893) is 1.2 GB. I am checking further with Oracle if this patch can help resolve our issue. 

Regards,
Amit

**Comment by lindamrigo** [comment]
This is now working.
