### ISSUE TITLE
INT - Saved favorites go to 12.1.3 Production 

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#80]
Saved favorites return application control to 12.1.3 Production from 12.2.10 INT.
![INT Saved Favorites](https://user-images.githubusercontent.com/85238444/124151983-1a213980-da61-11eb-8c99-cf375671712a.JPG)
![Saved Favorites returned to Production](https://user-images.githubusercontent.com/85238444/124151994-1beafd00-da61-11eb-8cb0-c81b2792f4a0.JPG)

**Comment by lindamrigo** [comment]
Also missing the ability to manage favorites
![manage favorites](https://user-images.githubusercontent.com/85238444/124153723-bb5cbf80-da62-11eb-84f0-71a675820731.JPG)

**Comment by lindamrigo** [comment]
This works the same in 12.1.3. Wants you to log back into production

**Comment by vinaytalasila** [comment]
Just an update...Amit will try to remove and add the favorites again in INT instance and check whether it works or not. If it works then he will prepare a document how to do that so the individual users can do that in the non-production instances.

Thanks
Vinay Talasila

**Comment by amitjori** [comment]
Hi Team,

We have currently disabled the favourite option in all non-prod 12.2.10 instances Individual users will have to update/maintain  the the url's added under favourites.

Regards,
Amit

**Comment by vinaytalasila** [comment]
@amitjori: As per our today's issues status meeting update, could you please mention the profile option name and the value that you did setup (site or responsibility or user level etc)  in all the non-prod 12.2.10 instances so that in the future SBS team will maintain that profile option value in their post clone steps in the non-prod instances.

After you update that information, please close this issue.

Thanks
Vinay Talasila

**Comment by amitjori** [comment]
Disabled favourite option in all 12.2.10 non production instances by setting the profile option FND: Disable Navigator and Favorites Rich Menu to True.
